### ISSUE TITLE
contents of env.yaml

### ISSUE THREAD

**Issue by jayita13** [TobeTek/deploy-gradio-ml-on-gcp#1]
Could you specify what env.yaml should contain that you've specified in the end of app.yaml
includes:
 - env.yaml

Facing this error 
ERROR: gcloud crashed (IncludeFileNotFound): File env.yaml listed in includes directive

**Comment by jayita13** [comment]
@TobeTek awaiting your inputs here

**Comment by TobeTek** [comment]
> @TobeTek awaiting your inputs here

Hi @jayita13 !

Thanks for your interest in this project.
I'll be creating a PR shortly, with an `example.env.yaml` to give a template, but essentially, it contains my `HUGGING_FACE_TOKEN` to use in connecting to the text generation model.

**Comment by TobeTek** [comment]
> Facing this error
ERROR: gcloud crashed (IncludeFileNotFound): File env.yaml listed in includes directive

The error arises because the `env.yaml` file is missing. I believe creating the file, and leaving it blank, should resolve the error.

**Comment by jayita13** [comment]
@TobeTek thanks for the response
